BEGIN;
CREATE SCHEMA IF NOT EXISTS DEVOPS;
CREATE TABLE IF NOT EXISTS HELLO ( MESSAGE VARCHAR(256) );
ALTER TABLE HELLO OWNER TO devops;
DELETE FROM HELLO;
INSERT INTO HELLO VALUES ('Goodbye from Database');
DROP TABLE MESSAGES;

SELECT * INTO MESSAGES FROM HELLO;
ALTER TABLE MESSAGES OWNER TO devops;
COMMIT;
