---

- name: Add Ubuntu OpenJDK repo (for additional Java versions)
  apt_repository: repo='ppa:openjdk-r/ppa' state=present
  tags:
    - java

- name: Install java jre
  apt:
    pkg: openjdk-8-jre
    state: present
    update_cache: no
  tags:
    - java

- name: Install vim
  apt:
    pkg: vim
    state: present
    update_cache: no
  tags:
   - vim

- name: vim filetype indent off
  lineinfile:
    dest: /etc/vim/vimrc
    state: present
    line: 'filetype indent off'
    regexp: '^filetype ident'
  tags:
   - vim
